### ISSUE TITLE
How to embed highlights into pdf file?

### ISSUE THREAD

**Issue by xuey06** [ahrm/sioyek-documentation#3]
How can I save or embed my annotations (such like highlights) into local pdf file? I can use other pdf reader to see it.

**Comment by ahrm** [comment]
We have an `embed_annotations` command that does that. (press ':' and type `embed_annotations`)

**Comment by xuey06** [comment]
> We have an `embed_annotations` command that does that. (press ':' and type `embed_annotations`)

Thank you.
